[env:aura_esp32s3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_src_filter = +<main.cpp> -<c3_main.cpp>
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
build_flags =
    -DBOARD_HAS_PSRAM
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=9
    -DTFT_RST=8
    -DTFT_BL=7
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=27000000

[env:aura_esp32c3_phone]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
build_src_filter = -<main.cpp> +<c3_main.cpp>
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^6.21.5
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=6
    -DTFT_SCLK=4
    -DTFT_CS=7
    -DTFT_DC=5
    -DTFT_RST=3
    -DTFT_BL=-1
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=27000000
